create table if not exists public.spacebring_finance_snapshots (
  id bigint generated by default as identity primary key,
  period_start date not null,
  period_end date not null,
  successful_value numeric(14,2) not null default 0,
  successful_count integer not null default 0,
  invoice_value numeric(14,2) not null default 0,
  booking_value numeric(14,2) not null default 0,
  subscription_value numeric(14,2) not null default 0,
  custom_value numeric(14,2) not null default 0,
  failed_value numeric(14,2) not null default 0,
  failed_count integer not null default 0,
  canceled_value numeric(14,2) not null default 0,
  canceled_count integer not null default 0,
  recovered_value numeric(14,2) not null default 0,
  recovered_attempts integer not null default 0,
  source text not null default 'spacebring',
  synced_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb,
  unique(period_start, period_end, source)
);

alter table public.spacebring_finance_snapshots enable row level security;
revoke all on table public.spacebring_finance_snapshots from anon, authenticated;
create index if not exists idx_spacebring_finance_snapshots_period_end on public.spacebring_finance_snapshots(period_end desc);
create index if not exists idx_spacebring_finance_snapshots_synced_at on public.spacebring_finance_snapshots(synced_at desc);
